In [1]:
import pandas as pd
from decimal import Decimal
import json
import numpy as np
from pprint import pprint
from carbon import CarbonSimulatorUI, __version__, __date__
print(f"Carbon Version v{__version__} ({__date__})", )

Carbon Version v2.0-beta3 (12/Dec/2022)

# Carbon Simulation - Demo-5-7 Simulator Import_Export NEW

Here we demonstrate the preferred setup to import and export json test files from the simulator using the new format

In [2]:
# Import Code
def load_json(filename):     
    '''
    :filename:  the convention is to specify the trade by source or trade by target in the filename i.e. tradeByTargetAmount.json
                this is necessary as the `is_by_target` field specifies the trade direction for the actionList
    '''   
    f = open(filename , "r")
    bm = f.read()
    loaded_json = json.loads(bm)
    f.close()
    return(loaded_json)

def decimalize_dict(dicta):
    deci_dict = {}
    for k,v in dicta.items():
        if k != 'token':
            v = Decimal(v)
        deci_dict[k] = v
    return(deci_dict)

def calc_y_int(liquidity, highestRate, lowestRate, marginalRate):
    return(liquidity * (highestRate.sqrt() - lowestRate.sqrt()) / (marginalRate.sqrt() - lowestRate.sqrt()))

def parse_order(order0, order_count):
    order0 = decimalize_dict(order0)
    order0['order'] = order_count
    order0_df = pd.DataFrame.from_dict(order0, 'index', columns=[f'{order_count}'])
    return(order0_df)

def parse_strategy(strategy, strat_count, order_count):
    orders = pd.DataFrame()
    orderList = strategy['orders']
    for order in orderList:
        order_df = parse_order(order, order_count)
        orders = pd.concat([orders,order_df.T])
        order_count += 1
    orders['strategy'] = strat_count
    strat_count += 1
    return(orders, strat_count, order_count)

def format_json_as_df(input_json, scenario_index = 0):
    '''
    :json:             the loaded json file
    :scenario_index:   each json file has multiple scenarios, make a selection
    '''
    actionList = input_json[scenario_index]['tradeActions']
    is_by_target = input_json[scenario_index]['tradeByTargetAmount']
    sourceToken = input_json[scenario_index]['sourceToken']
    targetToken = input_json[scenario_index]['targetToken']
    
    print(f'The number of scenarios is {len(input_json)}')
    print(f'You selected scenario: {scenario_index}')  
    print(f'The number of actions in this scenario are: {len(actionList)}')

    if scenario_index >= len(input_json):
        print('Please selected a valid scenario_index')
        return()
    else:
        strats = pd.DataFrame()
        strat_count = 0
        order_count = 0
        for strategy in input_json[scenario_index]['strategies']:
            orders, strat_count, order_count = parse_strategy(strategy, strat_count, order_count)
            strats = pd.concat([strats, orders])
        return(strats, actionList, is_by_target, sourceToken, targetToken)

def setup_initial_orders(strats, sourceToken, targetToken):
    FastSim = CarbonSimulatorUI(pair=f"{sourceToken}/{targetToken}", verbose=False, matching_method='exact', raiseonerror=True)

    if strats.token[0] == sourceToken:
        for i in strats.order[::2]:
            FastSim.add_strategy(
                tkn=f'{sourceToken}',
                amt_sell=Decimal(str(strats.liquidity[i])),
                psell_start=1/strats.highestRate[i],
                psell_end=1/strats.lowestRate[i],
                psell_marginal=1/strats.marginalRate[i],
                amt_buy=strats.liquidity[i+1],
                pbuy_start=strats.highestRate[i+1],
                pbuy_end=strats.lowestRate[i+1],
                pbuy_marginal=strats.marginalRate[i+1],
            )
    else:
        for i in strats.order[::2]:
            FastSim.add_strategy(
                tkn=f'{targetToken}',
                amt_sell=Decimal(str(strats.liquidity[i])),
                psell_start=strats.highestRate[i],
                psell_end=strats.lowestRate[i],
                psell_marginal=strats.marginalRate[i],
                amt_buy=strats.liquidity[i+1],
                pbuy_start=1/strats.highestRate[i+1],
                pbuy_end=1/strats.lowestRate[i+1],
                pbuy_marginal=1/strats.marginalRate[i+1],
            )

    initial_orders_import = FastSim.state()['orders']
    return(FastSim, initial_orders_import)

def parse_actions(Sim, actionList, strats, is_by_target, sourceToken, targetToken):
    '''
    parse_actions processes trades from the actionList

    :Sim:           the specific simulator environment to trade against
    :actionList:    the list of actions provides from the test json
    :strats:        the preprocessed dataframe of strategies from the test json
    :is_by_target:  the specification of trading by target or by source
    '''
    print(f"Trading by Target: {is_by_target}; Source Token is {sourceToken}; Target Token is {targetToken}")

    for action in actionList:
        strategyId = int(action['strategyId']) - 1
        targetStrategy = strats.query(f"strategy=={strategyId}")
        tokenAmount = Decimal(action['tokenAmount'])
        # print(strategyId, tokenAmount)
        if not is_by_target:
            targetOrderId = targetStrategy.query(f"token=='{targetToken}'")['order'].values[0]
            Sim.amm_buys(sourceToken, tokenAmount, execute=True, use_positions=[targetOrderId], use_positions_matchlevel=[targetOrderId])['trades']  # route_trade_by_source
            # print(sourceToken, targetOrderId, tokenAmount)
        else:
            targetOrderId = targetStrategy.query(f"token=='{targetToken}'")['order'].values[0]
            Sim.amm_sells(targetToken, tokenAmount, execute=True, use_positions=[targetOrderId], use_positions_matchlevel=[targetOrderId])['trades']  # route_trade_by_target
            # print(targetToken, targetOrderId, tokenAmount)
        
def verify_json(filename, accuracy=7):
    input_json = load_json(filename)
    for scenario_index in range(len(input_json)):
        print("\n")
        strats, actionList, is_by_target, sourceToken, targetToken = format_json_as_df(input_json, scenario_index = scenario_index)
        FastSim, initial_orders_import = setup_initial_orders(strats, sourceToken, targetToken)
        parse_actions(FastSim, actionList, strats, is_by_target, sourceToken, targetToken)
        final_orders_import = FastSim.state()['orders']
        for strat_index in final_orders_import.index[::2]:
            # print(f"{final_orders_import.y[strat_index]:.{accuracy}f}", f"{float(input_json[scenario_index]['strategies'][strat_index//2]['orders'][0]['newLiquidity']):.{accuracy}f}")
            assert(f"{final_orders_import.y[strat_index]:.{accuracy}f}" == f"{float(input_json[scenario_index]['strategies'][strat_index//2]['orders'][0]['newLiquidity']):.{accuracy}f}")
            # print(f"{final_orders_import.y[strat_index+1]:.{accuracy}f}", f"{float(input_json[scenario_index]['strategies'][strat_index//2]['orders'][1]['newLiquidity']):.{accuracy}f}")
            assert(f"{final_orders_import.y[strat_index+1]:.{accuracy}f}" == f"{float(input_json[scenario_index]['strategies'][strat_index//2]['orders'][1]['newLiquidity']):.{accuracy}f}")
    print("\n----------All Tests Passed!----------\n")

def verify_json2(filename, accuracy=12):
    misses = {}
    input_json = load_json(filename)
    for scenario_index in range(len(input_json)):
        print("\n")
        strats, actionList, is_by_target, sourceToken, targetToken = format_json_as_df(input_json, scenario_index = scenario_index)
        FastSim, initial_orders_import = setup_initial_orders(strats, sourceToken, targetToken)
        parse_actions(FastSim, actionList, strats, is_by_target, sourceToken, targetToken)
        final_orders_import = FastSim.state()['orders']
        sub_misses = []
        for strat_index in final_orders_import.index[::2]:
            if not f"{final_orders_import.y[strat_index]:.{accuracy}f}" == f"{float(input_json[scenario_index]['strategies'][strat_index//2]['orders'][0]['newLiquidity']):.{accuracy}f}":
                sub_misses += [(f"{final_orders_import.y[strat_index]:.{accuracy}f}", f"{float(input_json[scenario_index]['strategies'][strat_index//2]['orders'][0]['newLiquidity']):.{accuracy}f}")]
            
            if not f"{final_orders_import.y[strat_index+1]:.{accuracy}f}" == f"{float(input_json[scenario_index]['strategies'][strat_index//2]['orders'][1]['newLiquidity']):.{accuracy}f}":
                sub_misses += [(f"{final_orders_import.y[strat_index+1]:.{accuracy}f}", f"{float(input_json[scenario_index]['strategies'][strat_index//2]['orders'][1]['newLiquidity']):.{accuracy}f}")]
        misses[scenario_index] = sub_misses
    return(misses)

# Export Code
def generate_json_actions_new(Sim, trade_a):

    json_actions = {}
    sub_actions_list = []

    if trade_a['success'] & trade_a['trades'].exec.all():
        subdf = trade_a['trades'].query('subid!="A"').copy()
        subdf.reset_index(inplace=True, drop=True)
        trade_is_by_target = trade_a['is_by_target']
        tkn = trade_a['tkn_sold']
        sourceToken = Sim.carbon_pair.other(tkn)
        targetToken = tkn

        print(f'trade_is_by_target: {trade_is_by_target}')
        for i in subdf.index:
            sub_actions = {}
            sub_actions['strategyId'] = f"{int((subdf.routeix[i]//2) + 1)}" # plus one to encode for contracts
            if trade_is_by_target:
                sub_actions['tokenAmount'] = f"{subdf.amt1[i]:.12f}"
            else:
                sub_actions['tokenAmount'] = f"{subdf.amt2[i]:.12f}"
            sub_actions_list += [sub_actions]
            
    json_actions['tradeActions'] = sub_actions_list
    return(json_actions, trade_is_by_target, sourceToken, targetToken)

def generate_json_strategies_new(initial_orders, final_orders):
    json_strats = {}
    json_orders = {}
    json_orders_list = []
    sub_dict_list = []
    for i in initial_orders.index[::2]:
        json_orders = {} 
        sub_dict0 = {}
        sub_dict0['token'] = initial_orders.tkn[i]
        sub_dict0['liquidity'] = f"{initial_orders.y[i]:.12f}"
        sub_dict0['lowestRate'] = f"{1/(initial_orders.p_end[i]):.12f}"  # - 0.000000001
        sub_dict0['highestRate'] = f"{(1/initial_orders.p_start[i]):.12f}" # + 0.000000001
        sub_dict0['marginalRate'] = f"{(1/initial_orders.p_marg[i]):.12f}"
        sub_dict0['newLiquidity'] = f"{final_orders.y[i]:.12f}"
        sub_dict0['newMarginalRate'] = f"{(1/final_orders.p_marg[i]):.12f}"
        
        sub_dict1 = {}   
        sub_dict1['token'] = initial_orders.tkn[i+1]
        sub_dict1['liquidity'] = f"{initial_orders.y[i+1]:.12f}" 
        sub_dict1['lowestRate'] = f"{((initial_orders.p_end[i+1])):.12f}" # + 0.000000001
        sub_dict1['highestRate'] = f"{((initial_orders.p_start[i+1])):.12f}" # - 0.000000001
        sub_dict1['marginalRate'] = f"{(initial_orders.p_marg[i+1]):.12f}"
        sub_dict1['newLiquidity'] = f"{final_orders.y[i+1]:.12f}"
        sub_dict1['newMarginalRate'] = f"{(final_orders.p_marg[i+1]):.12f}"
        json_orders['orders'] = [sub_dict0,sub_dict1]
        json_orders_list += [json_orders]
    json_strats['strategies'] = json_orders_list
    return(json_strats)

def format_simulator_json_new(json_strats, json_actions, trade_is_by_target, sourceToken, targetToken):
    json_simulator = []
    simulator_setup = {}
    simulator_setup['tradeByTargetAmount'] = True if trade_is_by_target else False
    simulator_setup['sourceToken'] = sourceToken
    simulator_setup['targetToken'] = targetToken
    simulator_setup.update({**json_strats, **json_actions})
    json_simulator += [simulator_setup]
    return(json_simulator)

# To Import Json and Verify against simulator

In [3]:
filename = 'ArbitraryTrade.json'
verify_json(filename, accuracy=7)
# misses = verify_json2(filename, accuracy=12)

The number of scenarios is 240
You selected scenario: 0
The number of actions in this scenario are: 1
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 1
The number of actions in this scenario are: 2
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 2
The number of actions in this scenario are: 3
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 3
The number of actions in this scenario are: 4
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 4
The number of actions in this scenario are: 5
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 5
The number of actions in this scenario are: 6
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 6
The number of actions in this scenario are: 7
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 7
The number of actions in this scenario are: 8
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 8
The number of actions in this scenario are: 9
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 9
The number of actions in this scenario are: 10
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 10
The number of actions in this scenario are: 1
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 11
The number of actions in this scenario are: 2
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 12
The number of actions in this scenario are: 3
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 13
The number of actions in this scenario are: 4
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 14
The number of actions in this scenario are: 5
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 15
The number of actions in this scenario are: 6
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 16
The number of actions in this scenario are: 7
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 17
The number of actions in this scenario are: 8
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 18
The number of actions in this scenario are: 9
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 19
The number of actions in this scenario are: 10
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 20
The number of actions in this scenario are: 1
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 21
The number of actions in this scenario are: 2
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 22
The number of actions in this scenario are: 3
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 23
The number of actions in this scenario are: 4
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 24
The number of actions in this scenario are: 5
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 25
The number of actions in this scenario are: 6
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 26
The number of actions in this scenario are: 7
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 27
The number of actions in this scenario are: 8
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 28
The number of actions in this scenario are: 9
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 29
The number of actions in this scenario are: 10
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 30
The number of actions in this scenario are: 1
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 31
The number of actions in this scenario are: 2
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 32
The number of actions in this scenario are: 3
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 33
The number of actions in this scenario are: 4
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 34
The number of actions in this scenario are: 5
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 35
The number of actions in this scenario are: 6
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 36
The number of actions in this scenario are: 7
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 37
The number of actions in this scenario are: 8
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 38
The number of actions in this scenario are: 9
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 39
The number of actions in this scenario are: 10
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 40
The number of actions in this scenario are: 1
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 41
The number of actions in this scenario are: 2
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 42
The number of actions in this scenario are: 3
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 43
The number of actions in this scenario are: 4
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 44
The number of actions in this scenario are: 5
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 45
The number of actions in this scenario are: 6
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 46
The number of actions in this scenario are: 7
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 47
The number of actions in this scenario are: 8
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 48
The number of actions in this scenario are: 9
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 49
The number of actions in this scenario are: 10
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 50
The number of actions in this scenario are: 1
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 51
The number of actions in this scenario are: 2
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 52
The number of actions in this scenario are: 3
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 53
The number of actions in this scenario are: 4
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 54
The number of actions in this scenario are: 5
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 55
The number of actions in this scenario are: 6
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 56
The number of actions in this scenario are: 7
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 57
The number of actions in this scenario are: 8
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 58
The number of actions in this scenario are: 9
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 59
The number of actions in this scenario are: 10
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 60
The number of actions in this scenario are: 1
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 61
The number of actions in this scenario are: 2
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 62
The number of actions in this scenario are: 3
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 63
The number of actions in this scenario are: 4
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 64
The number of actions in this scenario are: 5
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 65
The number of actions in this scenario are: 6
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 66
The number of actions in this scenario are: 7
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 67
The number of actions in this scenario are: 8
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 68
The number of actions in this scenario are: 9
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 69
The number of actions in this scenario are: 10
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 70
The number of actions in this scenario are: 1
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 71
The number of actions in this scenario are: 2
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 72
The number of actions in this scenario are: 3
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 73
The number of actions in this scenario are: 4
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 74
The number of actions in this scenario are: 5
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 75
The number of actions in this scenario are: 6
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 76
The number of actions in this scenario are: 7
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 77
The number of actions in this scenario are: 8
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 78
The number of actions in this scenario are: 9
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 79
The number of actions in this scenario are: 10
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 80
The number of actions in this scenario are: 1
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 81
The number of actions in this scenario are: 2
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 82
The number of actions in this scenario are: 3
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 83
The number of actions in this scenario are: 4
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 84
The number of actions in this scenario are: 5
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 85
The number of actions in this scenario are: 6
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 86
The number of actions in this scenario are: 7
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 87
The number of actions in this scenario are: 8
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 88
The number of actions in this scenario are: 9
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 89
The number of actions in this scenario are: 10
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 90
The number of actions in this scenario are: 1
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 91
The number of actions in this scenario are: 2
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 92
The number of actions in this scenario are: 3
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 93
The number of actions in this scenario are: 4
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 94
The number of actions in this scenario are: 5
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 95
The number of actions in this scenario are: 6
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 96
The number of actions in this scenario are: 7
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 97
The number of actions in this scenario are: 8
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 98
The number of actions in this scenario are: 9
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 99
The number of actions in this scenario are: 10
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 100
The number of actions in this scenario are: 1
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 101
The number of actions in this scenario are: 2
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 102
The number of actions in this scenario are: 3
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 103
The number of actions in this scenario are: 4
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 104
The number of actions in this scenario are: 5
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 105
The number of actions in this scenario are: 6
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 106
The number of actions in this scenario are: 7
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 107
The number of actions in this scenario are: 8
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 108
The number of actions in this scenario are: 9
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 109
The number of actions in this scenario are: 10
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 110
The number of actions in this scenario are: 1
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 111
The number of actions in this scenario are: 2
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 112
The number of actions in this scenario are: 3
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 113
The number of actions in this scenario are: 4
Trading by Target: False; Source Token is TKN0; Target Token is TKN1


The number of scenarios is 240
You selected scenario: 114
The number of actions in this scenario are: 5

# To Create New Scenario and Export to Json

## Initialize a simulator and add some strategies

In [4]:
# New Sim
FastSim = CarbonSimulatorUI(pair="ETH/USDC", verbose=False, matching_method='exact', raiseonerror=True)

In [5]:
# Add strategies
FastSim.add_strategy("ETH", 10, 2000, 2500, 10000, 1040, 1020, "ETH/USDC", 2100, 1030)
FastSim.add_strategy("ETH", 10, 2010, 2810, 10000, 1510, 1210, "ETH/USDC", 2100, 1250)
FastSim.add_strategy("ETH", 10, 2020, 2220, 10000, 1060, 1050, "ETH/USDC", 2200, 1055)
FastSim.add_strategy("ETH", 10, 2030, 2060, 10000, 1750, 1055, "ETH/USDC", 2035, 1700)
FastSim.add_strategy("ETH", 10, 2040, 2080, 10000, 1250, 1040, "ETH/USDC", 2050, 1050)

# Snapshot the simulator orders
initial_orders = FastSim.state()['orders']

In [6]:
initial_orders

,id,pair,tkn,y_int,y,y_unit,disabled,p_start,p_end,p_marg,p_unit,lid
0,0,ETHUSDC,ETH,12.958031,10.0,ETH,False,2000.0,2500.0,2100.0,USDC per ETH,1
1,1,ETHUSDC,USDC,19951.572996,10000.0,USDC,False,1040.0,1020.0,1030.0,USDC per ETH,0
2,2,ETHUSDC,ETH,11.633958,10.0,ETH,False,2010.0,2810.0,2100.0,USDC per ETH,3
3,3,ETHUSDC,USDC,71432.102199,10000.0,USDC,False,1510.0,1210.0,1250.0,USDC per ETH,2
4,4,ETHUSDC,ETH,106.581944,10.0,ETH,False,2020.0,2220.0,2200.0,USDC per ETH,5
5,5,ETHUSDC,USDC,19976.331261,10000.0,USDC,False,1060.0,1050.0,1055.0,USDC per ETH,4
6,6,ETHUSDC,ETH,12.022136,10.0,ETH,False,2030.0,2060.0,2035.0,USDC per ETH,7
7,7,ETHUSDC,USDC,10687.914210,10000.0,USDC,False,1750.0,1055.0,1700.0,USDC per ETH,6
8,8,ETHUSDC,ETH,13.382254,10.0,ETH,False,2040.0,2080.0,2050.0,USDC per ETH,9
9,9,ETHUSDC,USDC,200831.310629,10000.0,USDC,False,1250.0,1040.0,1050.0,USDC per ETH,8

## Do a trade and process it into an actionList

In [7]:
# Do a trade
trade_a = FastSim.amm_sells('ETH', 29, execute=True) # route_trade_by_target
# trade_a = FastSim.amm_buys('ETH', 15, execute=True) # route_trade_by_source
# trade_a = FastSim.amm_sells('USDC', 50000, execute=True) # route_trade_by_target
# trade_a = FastSim.amm_buys('USDC', 30000, execute=True) # route_trade_by_source

# Generate the actions component of the json
json_actions, trade_is_by_target, sourceToken, targetToken  = generate_json_actions_new(FastSim, trade_a)
sourceToken, targetToken

trade_is_by_target: True

('USDC', 'ETH')

In [8]:
# Snapshot the orders
final_orders = FastSim.state()['orders']
final_orders

,id,pair,tkn,y_int,y,y_unit,disabled,p_start,p_end,p_marg,p_unit,lid
0,0,ETHUSDC,ETH,12.958031,7.024559,ETH,False,2000.0,2500.0,2208.350060,USDC per ETH,1
1,1,ETHUSDC,USDC,19951.572996,16407.593124,USDC,False,1040.0,1020.0,1036.433236,USDC per ETH,0
2,2,ETHUSDC,ETH,11.633958,8.166987,ETH,False,2010.0,2810.0,2208.350060,USDC per ETH,3
3,3,ETHUSDC,USDC,71432.102199,13947.381198,USDC,False,1510.0,1210.0,1265.968579,USDC per ETH,2
4,4,ETHUSDC,ETH,106.581944,5.808453,ETH,False,2020.0,2220.0,2208.350060,USDC per ETH,5
5,5,ETHUSDC,USDC,19976.331261,19238.885565,USDC,False,1060.0,1050.0,1059.629998,USDC per ETH,4
6,6,ETHUSDC,ETH,12.022136,0.000000,ETH,False,2030.0,2060.0,2060.000000,USDC per ETH,7
7,7,ETHUSDC,USDC,30474.618434,30474.618434,USDC,False,1750.0,1055.0,1750.000000,USDC per ETH,6
8,8,ETHUSDC,ETH,13.382254,0.000000,ETH,False,2040.0,2080.0,2080.000000,USDC per ETH,9
9,9,ETHUSDC,USDC,200831.310629,30649.455199,USDC,False,1250.0,1040.0,1070.800866,USDC per ETH,8

## Generate the strategies component of the json

In [9]:
# Generate the strategies component of the json
json_strats = generate_json_strategies_new(initial_orders, final_orders)

## Combine and format the jsons

In [10]:
json_simulator = format_simulator_json_new(json_strats, json_actions, trade_is_by_target, sourceToken, targetToken)
# pprint(json_simulator, sort_dicts=False)

## Optionally Save

In [11]:
from datetime import datetime
str_date = datetime.today().strftime("%Y%m%d")
unique_id = datetime.now().strftime("%f")
    
export_filename = f"{str_date}_test_{unique_id}.json"

out_file = open(export_filename, "w")
json.dump(json_simulator, out_file, indent=4)
out_file.close()

print(f'Saved as {export_filename}')

Saved as 20221227_test_598380.json

# To Import json and Evaluate Step-wise

First we load the json test file and return a df of the strategies and a list of actions

** If you want to use a specific scenario you need to specify the scenario_index here **

In [12]:
# Specify the scenario_index for a different scenario
# filename=export_filename
filename = 'ArbitraryTrade.json'
scenario_index = 17

input_json = load_json(filename)
strats, actionList, is_by_target, sourceToken, targetToken = format_json_as_df(input_json, scenario_index = scenario_index)
strats

The number of scenarios is 240
You selected scenario: 17
The number of actions in this scenario are: 8

,token,liquidity,lowestRate,highestRate,marginalRate,newLiquidity,newMarginalRate,order,strategy
0,TKN1,811454,8,9,8.926272154378,802532.958938149005,8.915813034918,0,0
1,TKN0,2950006,1,2,1.994880400689,2951006,1.995275319802,1,0
2,TKN1,886382,9,10,9.878651104636,866644.718474130513,9.858640565021,2,1
3,TKN0,3908757,2,3,2.988345409139,3910757,2.988901743097,3,1
4,TKN1,971216,10,11,10.852675525964,938701.667985593085,10.823565363766,4,2
5,TKN0,4857523,3,4,3.982493954497,4860523,3.983143671371,5,2
6,TKN1,1071798,11,12,11.846118925741,1024489.602111664287,11.808110554978,6,3
7,TKN0,5802276,4,5,4.977995855342,5806276,4.978706927644,7,3
8,TKN1,1194086,12,13,12.857877698960,1129913.860359044172,12.811020924336,8,4
9,TKN0,6748988,5,6,5.975134668541,6753988,5.975889280009,9,4
10,TKN1,1344150,13,14,13.887474933789,1260992.583529681311,13.831719963067,10,5
11,TKN0,7703647,6,7,6.974053998345,7709647,6.974841182972,11,5
12,TKN1,1528157,14,15,14.934803005163,1423840.331502165291,14.870029806881,12,6
13,TKN0,8672252,7,8,7.974835205438,8679252,7.975647724709,13,6
14,TKN1,1752384,15,16,16,1624680.200090229295,15.926035655659,14,7
15,TKN0,9660811,8,9,8.977528490920,9668811,8.978361313042,15,7
16,TKN1,1869840,16,17,17,1869840,17,16,8
17,TKN0,10684348,9,10,9.983017270256,10684348,9.983017270256,17,8
18,TKN1,1985296,17,18,18,1985296,18,18,9
19,TKN0,11741896,10,11,10.990503836203,11741896,10.990503836203,19,9

# Initialize the Simulator and create the orders
Here the orders are entered into the simulator and the prices for one side of the strategy are flipped to coincide with the price convention

In [13]:
pd.set_option('display.float_format', lambda x: '%.5f' % x)

FastSim, initial_orders_import = setup_initial_orders(strats, sourceToken, targetToken)
initial_orders_import

,id,pair,tkn,y_int,y,y_unit,disabled,p_start,p_end,p_marg,p_unit,lid
0,0,TKN0TKN1,TKN1,874192.00000,811454.00000,TKN1,False,9.00000,8.00000,8.92627,TKN1 per TKN0,1
1,1,TKN0TKN1,TKN0,2962962.00000,2950006.00000,TKN0,False,0.50000,1.00000,0.50128,TKN1 per TKN0,0
2,2,TKN0TKN1,TKN1,1005648.00000,886382.00000,TKN1,False,10.00000,9.00000,9.87865,TKN1 per TKN0,3
3,3,TKN0TKN1,TKN0,3950616.00000,3908757.00000,TKN0,False,0.33333,0.50000,0.33463,TKN1 per TKN0,2
4,4,TKN0TKN1,TKN1,1135104.00000,971216.00000,TKN1,False,11.00000,10.00000,10.85268,TKN1 per TKN0,5
5,5,TKN0TKN1,TKN0,4938270.00000,4857523.00000,TKN0,False,0.25000,0.33333,0.25110,TKN1 per TKN0,4
6,6,TKN0TKN1,TKN1,1262560.00000,1071798.00000,TKN1,False,12.00000,11.00000,11.84612,TKN1 per TKN0,7
7,7,TKN0TKN1,TKN0,5925924.00000,5802276.00000,TKN0,False,0.20000,0.25000,0.20088,TKN1 per TKN0,6
8,8,TKN0TKN1,TKN1,1388016.00000,1194086.00000,TKN1,False,13.00000,12.00000,12.85788,TKN1 per TKN0,9
9,9,TKN0TKN1,TKN0,6913578.00000,6748988.00000,TKN0,False,0.16667,0.20000,0.16736,TKN1 per TKN0,8
10,10,TKN0TKN1,TKN1,1511472.00000,1344150.00000,TKN1,False,14.00000,13.00000,13.88747,TKN1 per TKN0,11
11,11,TKN0TKN1,TKN0,7901232.00000,7703647.00000,TKN0,False,0.14286,0.16667,0.14339,TKN1 per TKN0,10
12,12,TKN0TKN1,TKN1,1632928.00000,1528157.00000,TKN1,False,15.00000,14.00000,14.93480,TKN1 per TKN0,13
13,13,TKN0TKN1,TKN0,8888886.00000,8672252.00000,TKN0,False,0.12500,0.14286,0.12539,TKN1 per TKN0,12
14,14,TKN0TKN1,TKN1,1752384.00000,1752384.00000,TKN1,False,16.00000,15.00000,16.00000,TKN1 per TKN0,15
15,15,TKN0TKN1,TKN0,9876540.00000,9660811.00000,TKN0,False,0.11111,0.12500,0.11139,TKN1 per TKN0,14
16,16,TKN0TKN1,TKN1,1869840.00000,1869840.00000,TKN1,False,17.00000,16.00000,17.00000,TKN1 per TKN0,17
17,17,TKN0TKN1,TKN0,10864194.00000,10684348.00000,TKN0,False,0.10000,0.11111,0.10017,TKN1 per TKN0,16
18,18,TKN0TKN1,TKN1,1985296.00000,1985296.00000,TKN1,False,18.00000,17.00000,18.00000,TKN1 per TKN0,19
19,19,TKN0TKN1,TKN0,11851848.00000,11741896.00000,TKN0,False,0.09091,0.10000,0.09099,TKN1 per TKN0,18

# Parse the actions to perform the trades

In [14]:
parse_actions(FastSim, actionList, strats, is_by_target, sourceToken, targetToken)

FastSim.state()['trades']

Trading by Target: False; Source Token is TKN0; Target Token is TKN1

,uid,id,subid,note,aggr,exec,limitfail,amt1,tkn1,amt2,tkn2,pair,routeix,nroutes,price,p_unit
0,0.0,0,0,route #0,False,True,None,8921.04106,TKN1,1000.00000,TKN0,TKN0TKN1,0,1,8.92104,TKN1 per TKN0
0,0,0,A,AMM sells 8921TKN1 buys 1000TKN0,True,True,None,8921.04106,TKN1,1000.00000,TKN0,TKN0TKN1,[0],1,8.92104,TKN1 per TKN0
0,1.0,1,0,route #2,False,True,None,19737.28153,TKN1,2000.00000,TKN0,TKN0TKN1,2,1,9.86864,TKN1 per TKN0
0,1,1,A,AMM sells 19737TKN1 buys 2000TKN0,True,True,None,19737.28153,TKN1,2000.00000,TKN0,TKN0TKN1,[2],1,9.86864,TKN1 per TKN0
0,2.0,2,0,route #4,False,True,None,32514.33201,TKN1,3000.00000,TKN0,TKN0TKN1,4,1,10.83811,TKN1 per TKN0
0,2,2,A,AMM sells 32514TKN1 buys 3000TKN0,True,True,None,32514.33201,TKN1,3000.00000,TKN0,TKN0TKN1,[4],1,10.83811,TKN1 per TKN0
0,3.0,3,0,route #6,False,True,None,47308.39789,TKN1,4000.00000,TKN0,TKN0TKN1,6,1,11.82710,TKN1 per TKN0
0,3,3,A,AMM sells 47308TKN1 buys 4000TKN0,True,True,None,47308.39789,TKN1,4000.00000,TKN0,TKN0TKN1,[6],1,11.82710,TKN1 per TKN0
0,4.0,4,0,route #8,False,True,None,64172.13964,TKN1,5000.00000,TKN0,TKN0TKN1,8,1,12.83443,TKN1 per TKN0
0,4,4,A,AMM sells 64172TKN1 buys 5000TKN0,True,True,None,64172.13964,TKN1,5000.00000,TKN0,TKN0TKN1,[8],1,12.83443,TKN1 per TKN0
0,5.0,5,0,route #10,False,True,None,83157.41647,TKN1,6000.00000,TKN0,TKN0TKN1,10,1,13.85957,TKN1 per TKN0
0,5,5,A,AMM sells 83157TKN1 buys 6000TKN0,True,True,None,83157.41647,TKN1,6000.00000,TKN0,TKN0TKN1,[10],1,13.85957,TKN1 per TKN0
0,6.0,6,0,route #12,False,True,None,104316.66850,TKN1,7000.00000,TKN0,TKN0TKN1,12,1,14.90238,TKN1 per TKN0
0,6,6,A,AMM sells 104317TKN1 buys 7000TKN0,True,True,None,104316.66850,TKN1,7000.00000,TKN0,TKN0TKN1,[12],1,14.90238,TKN1 per TKN0
0,7.0,7,0,route #14,False,True,None,127703.79991,TKN1,8000.00000,TKN0,TKN0TKN1,14,1,15.96297,TKN1 per TKN0
0,7,7,A,AMM sells 127704TKN1 buys 8000TKN0,True,True,None,127703.79991,TKN1,8000.00000,TKN0,TKN0TKN1,[14],1,15.96297,TKN1 per TKN0

# Display the status of the orders post-trade

In [15]:
pd.set_option('display.float_format', lambda x: '%.5f' % x)

final_orders_import = FastSim.state()['orders']
final_orders_import

,id,pair,tkn,y_int,y,y_unit,disabled,p_start,p_end,p_marg,p_unit,lid
0,0,TKN0TKN1,TKN1,874192.00000,802532.95894,TKN1,False,9.00000,8.00000,8.91581,TKN1 per TKN0,1
1,1,TKN0TKN1,TKN0,2962962.00000,2951006.00000,TKN0,False,0.50000,1.00000,0.50118,TKN1 per TKN0,0
2,2,TKN0TKN1,TKN1,1005648.00000,866644.71847,TKN1,False,10.00000,9.00000,9.85864,TKN1 per TKN0,3
3,3,TKN0TKN1,TKN0,3950616.00000,3910757.00000,TKN0,False,0.33333,0.50000,0.33457,TKN1 per TKN0,2
4,4,TKN0TKN1,TKN1,1135104.00000,938701.66799,TKN1,False,11.00000,10.00000,10.82357,TKN1 per TKN0,5
5,5,TKN0TKN1,TKN0,4938270.00000,4860523.00000,TKN0,False,0.25000,0.33333,0.25106,TKN1 per TKN0,4
6,6,TKN0TKN1,TKN1,1262560.00000,1024489.60211,TKN1,False,12.00000,11.00000,11.80811,TKN1 per TKN0,7
7,7,TKN0TKN1,TKN0,5925924.00000,5806276.00000,TKN0,False,0.20000,0.25000,0.20086,TKN1 per TKN0,6
8,8,TKN0TKN1,TKN1,1388016.00000,1129913.86036,TKN1,False,13.00000,12.00000,12.81102,TKN1 per TKN0,9
9,9,TKN0TKN1,TKN0,6913578.00000,6753988.00000,TKN0,False,0.16667,0.20000,0.16734,TKN1 per TKN0,8
10,10,TKN0TKN1,TKN1,1511472.00000,1260992.58353,TKN1,False,14.00000,13.00000,13.83172,TKN1 per TKN0,11
11,11,TKN0TKN1,TKN0,7901232.00000,7709647.00000,TKN0,False,0.14286,0.16667,0.14337,TKN1 per TKN0,10
12,12,TKN0TKN1,TKN1,1632928.00000,1423840.33150,TKN1,False,15.00000,14.00000,14.87003,TKN1 per TKN0,13
13,13,TKN0TKN1,TKN0,8888886.00000,8679252.00000,TKN0,False,0.12500,0.14286,0.12538,TKN1 per TKN0,12
14,14,TKN0TKN1,TKN1,1752384.00000,1624680.20009,TKN1,False,16.00000,15.00000,15.92604,TKN1 per TKN0,15
15,15,TKN0TKN1,TKN0,9876540.00000,9668811.00000,TKN0,False,0.11111,0.12500,0.11138,TKN1 per TKN0,14
16,16,TKN0TKN1,TKN1,1869840.00000,1869840.00000,TKN1,False,17.00000,16.00000,17.00000,TKN1 per TKN0,17
17,17,TKN0TKN1,TKN0,10864194.00000,10684348.00000,TKN0,False,0.10000,0.11111,0.10017,TKN1 per TKN0,16
18,18,TKN0TKN1,TKN1,1985296.00000,1985296.00000,TKN1,False,18.00000,17.00000,18.00000,TKN1 per TKN0,19
19,19,TKN0TKN1,TKN0,11851848.00000,11741896.00000,TKN0,False,0.09091,0.10000,0.09099,TKN1 per TKN0,18

In [16]:
accuracy = 12
for strat_index in final_orders_import.index[::2]:
    print(f"{final_orders_import.y[strat_index]:.{accuracy}f}", f"{float(input_json[scenario_index]['strategies'][strat_index//2]['orders'][0]['newLiquidity']):.{accuracy}f}")
    assert(f"{final_orders_import.y[strat_index]:.{accuracy}f}" == f"{float(input_json[scenario_index]['strategies'][strat_index//2]['orders'][0]['newLiquidity']):.{accuracy}f}")
    print(f"{final_orders_import.y[strat_index+1]:.{accuracy}f}", f"{float(input_json[scenario_index]['strategies'][strat_index//2]['orders'][1]['newLiquidity']):.{accuracy}f}")
    assert(f"{final_orders_import.y[strat_index+1]:.{accuracy}f}" == f"{float(input_json[scenario_index]['strategies'][strat_index//2]['orders'][1]['newLiquidity']):.{accuracy}f}")
print("\n----------All Tests Passed!----------\n")

802532.958938149037 802532.958938149037
2951006.000000000000 2951006.000000000000
866644.718474130495 866644.718474130495
3910757.000000000000 3910757.000000000000
938701.667985593085 938701.667985593085
4860523.000000000000 4860523.000000000000
1024489.602111664251 1024489.602111664251
5806276.000000000000 5806276.000000000000
1129913.860359044280 1129913.860359044280
6753988.000000000000 6753988.000000000000
1260992.583529681433 1260992.583529681200

AssertionError:

In [ ]:
misses = []
for strat_index in final_orders_import.index[::2]:
    print(f"{final_orders_import.y[strat_index]:.{accuracy}f}", f"{float(input_json[scenario_index]['strategies'][strat_index//2]['orders'][0]['newLiquidity']):.{accuracy}f}")
    if not f"{final_orders_import.y[strat_index]:.{accuracy}f}" == f"{float(input_json[scenario_index]['strategies'][strat_index//2]['orders'][0]['newLiquidity']):.{accuracy}f}":
        misses += [f"{final_orders_import.y[strat_index]:.{accuracy}f}" == f"{float(input_json[scenario_index]['strategies'][strat_index//2]['orders'][0]['newLiquidity']):.{accuracy}f}"]
    print(f"{final_orders_import.y[strat_index+1]:.{accuracy}f}", f"{float(input_json[scenario_index]['strategies'][strat_index//2]['orders'][1]['newLiquidity']):.{accuracy}f}")
    if not f"{final_orders_import.y[strat_index+1]:.{accuracy}f}" == f"{float(input_json[scenario_index]['strategies'][strat_index//2]['orders'][1]['newLiquidity']):.{accuracy}f}":
        misses += [f"{final_orders_import.y[strat_index+1]:.{accuracy}f}" == f"{float(input_json[scenario_index]['strategies'][strat_index//2]['orders'][1]['newLiquidity']):.{accuracy}f}"]
# print("\n----------All Tests Passed!----------\n")
print(len(misses))

In [ ]:
final_orders_import